// <auto-generated />
namespace WasterWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201408222226333_UserGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
